changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: "Новые возможности"
      labels:
        - enhancement
    - title: "Исправления ошибок"
      labels:
        - bug
    - title: "Документация"
      labels:
        - documentation
    - title: "CI/CD и инфраструктура"
      labels:
        - github-actions
    - title: "Зависимости"
      labels:
        - dependencies
    - title: "Другие изменения"
      labels:
        - "*"
