version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck      # Проверка неиспользованных ошибок
    - govet         # Стандартный vet
    - staticcheck   # Дополнительные проверки (включает gosimple, stylecheck)
    - ineffassign   # Неиспользуемые присваивания
    - unused        # Неиспользуемый код
    - misspell      # Опечатки в комментариях
    - revive        # Замена golint

  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true

    govet:
      disable:
        - fieldalignment  # Отключаем проверку выравнивания полей структур

    misspell:
      ignore-rules:
        - currate  # Намеренное название проекта (Currency Rate)

    revive:
      rules:
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning

    staticcheck:
      checks:
        - all
        - -ST1005  # Отключаем проверку капитализации ошибок (у нас русские сообщения)

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      # Исключить некоторые линтеры для тестов
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt         # Форматирование

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
