// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1) {
  return window['go']['app']['App']['Convert'](arg1);
}

export function GetRate(arg1, arg2) {
  return window['go']['app']['App']['GetRate'](arg1, arg2);
}

export function ShowAbout() {
  return window['go']['app']['App']['ShowAbout']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
