// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function Convert(arg1:app.ConvertRequest):Promise<app.ConvertResponse>;

export function GetRate(arg1:string,arg2:string):Promise<app.RateResponse>;

export function ShowAbout():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
